---
version: 0.2
phases:
  pre_build:
    commands:
      - cd functions/api
      - npm install
      - cd ../../
  build:
    commands:
      - echo Build started on `date`
      - cd functions/api
      - tsc
      - cd ../../
      - "/usr/local/bin/apex deploy"
  post_build:
    commands:
      - echo Build completed on `date`